# Generated by Django 5.1.3 on 2024-12-08 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_account_first_name_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='position_title',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.company')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.job'),
        ),
    ]
