# Generated by Django 5.1.3 on 2024-12-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
