# Generated by Django 5.1.3 on 2024-12-09 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_account_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.interview'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='job_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='project.jobapplication'),
        ),
    ]
