# Generated by Django 5.1.3 on 2024-12-09 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_jobapplication_interview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='interview',
        ),
        migrations.AlterField(
            model_name='interview',
            name='job_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.jobapplication'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.job'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=20),
        ),
    ]
