# Generated by Django 5.1.3 on 2024-12-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_jobapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='industry',
        ),
    ]
