# Generated by Django 5.1.3 on 2024-12-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_remove_job_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile',
        ),
    ]
